# Generated by Django 5.1.1 on 2024-09-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
