# Generated by Django 5.2.17 on 2026-10-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0002_voice_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voice',
            options={'verbose_name': 'Resident testimonial', 'verbose_name_plural': 'Resident testimonials'},
        ),
        migrations.AddField(
            model_name='voice',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Content (English)'),
        ),
        migrations.AddField(
            model_name='voice',
            name='description_zh_hans',
            field=models.TextField(blank=True, default='', verbose_name='Content (Simplified Chinese)'),
        ),
        migrations.AddField(
            model_name='voice',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Name (English)'),
        ),
        migrations.AddField(
            model_name='voice',
            name='name_zh_hans',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Name (Simplified Chinese)'),
        ),
        migrations.AlterField(
            model_name='voice',
            name='description',
            field=models.TextField(max_length=50, verbose_name='Content (Traditional Chinese)'),
        ),
        migrations.AlterField(
            model_name='voice',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='voice',
            name='name',
            field=models.TextField(max_length=30, verbose_name='Name (Traditional Chinese)'),
        ),
        migrations.AlterField(
            model_name='voice',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Photo'),
        ),
    ]
