# Generated by Django 5.1.1 on 2024-09-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0002_remove_booking_is_mvp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='title',
            field=models.CharField(choices=[('visiting', '預約參觀院舍'), ('booking', '預約到訪院舍選位')], max_length=20),
        ),
    ]
