# Generated by Django 5.1.1 on 2024-09-20 04:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0003_alter_booking_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='visit_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
