# Generated by Django 5.1.1 on 2024-09-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0006_alter_booking_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
