# Generated by Django 5.2.17 on 2026-10-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_new_title_alter_new_youtube_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': 'News item', 'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='new',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Content (English)'),
        ),
        migrations.AddField(
            model_name='new',
            name='description_zh_hans',
            field=models.TextField(blank=True, default='', verbose_name='Content (Simplified Chinese)'),
        ),
        migrations.AddField(
            model_name='new',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Title (English)'),
        ),
        migrations.AddField(
            model_name='new',
            name='title_zh_hans',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Title (Simplified Chinese)'),
        ),
        migrations.AlterField(
            model_name='new',
            name='description',
            field=models.TextField(blank=True, verbose_name='Content (Traditional Chinese)'),
        ),
        migrations.AlterField(
            model_name='new',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='new',
            name='list_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Publication date'),
        ),
        migrations.AlterField(
            model_name='new',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Photo 1'),
        ),
        migrations.AlterField(
            model_name='new',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Photo 2'),
        ),
        migrations.AlterField(
            model_name='new',
            name='photo_3',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Photo 3'),
        ),
        migrations.AlterField(
            model_name='new',
            name='photo_4',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Photo 4'),
        ),
        migrations.AlterField(
            model_name='new',
            name='photo_5',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Photo 5'),
        ),
        migrations.AlterField(
            model_name='new',
            name='photo_6',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Photo 6'),
        ),
        migrations.AlterField(
            model_name='new',
            name='photo_7',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Photo 7'),
        ),
        migrations.AlterField(
            model_name='new',
            name='photo_8',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Photo 8'),
        ),
        migrations.AlterField(
            model_name='new',
            name='photo_9',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Photo 9'),
        ),
        migrations.AlterField(
            model_name='new',
            name='photo_main',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Main photo'),
        ),
        migrations.AlterField(
            model_name='new',
            name='title',
            field=models.CharField(max_length=14, verbose_name='Title (Traditional Chinese)'),
        ),
        migrations.AlterField(
            model_name='new',
            name='youtube_link',
            field=models.URLField(blank=True, max_length=1000, verbose_name='YouTube URL'),
        ),
    ]
