# Generated by Django 5.1.1 on 2024-09-21 00:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('Bank Transfer', '銀行轉帳'), ('FPS', '轉數快轉帳(FPS)')], max_length=20)),
                ('depositslip_photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('message', models.TextField(max_length=50)),
                ('submit_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('resident_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='banks_by_resident_id', to='residents.resident')),
                ('resident_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='banks_by_resident_name', to='residents.resident')),
            ],
        ),
    ]
