# Generated by Django 5.1.1 on 2024-09-29 03:26

import banks.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_id', models.IntegerField()),
                ('resident_name', models.CharField(max_length=200)),
                ('resident_code', models.CharField(max_length=200)),
                ('payment_method', models.CharField(choices=[('Bank Transfer', '銀行轉帳'), ('FPS', '轉數快轉帳(FPS)')], max_length=20)),
                ('payment_month', models.CharField(choices=[('January', '1月份'), ('February', '2月份'), ('March', '3月份'), ('April', '4月份'), ('May', '5月份'), ('June', '6月份'), ('July', '7月份'), ('August', '8月份'), ('September', '9月份'), ('October', '10月份'), ('November', '11月份'), ('December', '12月份')], default=banks.models.current_month, max_length=20)),
                ('payment_year', models.CharField(choices=[('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030'), ('2031', '2031'), ('2032', '2032'), ('2033', '2033'), ('2034', '2034')], default=banks.models.current_year, max_length=20)),
                ('depositslip_photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('message', models.TextField(max_length=50)),
                ('uploaded_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
