# Generated by Django 5.1.1 on 2024-10-01 21:02

import banks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='payment_method',
            field=models.CharField(choices=[('銀行轉帳', '銀行轉帳'), ('轉數快轉帳(FPS)', '轉數快轉帳(FPS)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bank',
            name='payment_month',
            field=models.CharField(choices=[('1月份', '1月份'), ('2月份', '2月份'), ('3月份', '3月份'), ('4月份', '4月份'), ('5月份', '5月份'), ('6月份', '6月份'), ('7月份', '7月份'), ('8月份', '8月份'), ('9月份', '9月份'), ('10月份', '10月份'), ('11月份', '11月份'), ('12月份', '12月份')], default=banks.models.current_month, max_length=20),
        ),
    ]
