# Generated by Django 5.1.1 on 2024-09-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='depositslip_photo',
            field=models.FileField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
