# Generated by Django 5.1.1 on 2024-09-21 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='submit_date',
            new_name='uploaded_date',
        ),
    ]
