# Generated by Django 5.1.1 on 2024-10-07 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_alter_bank_payment_method_alter_bank_payment_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='message',
            new_name='comment',
        ),
    ]
