# Generated by Django 5.2.17 on 2026-10-06 17:16

import banks.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0003_rename_message_bank_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'verbose_name': 'Payment record', 'verbose_name_plural': 'Payment records'},
        ),
        migrations.AlterField(
            model_name='bank',
            name='comment',
            field=models.TextField(max_length=50, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='depositslip_photo',
            field=models.FileField(upload_to='photos/%Y/%m/%d/', verbose_name='Payment receipt'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='payment_method',
            field=models.CharField(choices=[('銀行轉帳', '銀行轉帳'), ('轉數快轉帳(FPS)', '轉數快轉帳(FPS)')], max_length=20, verbose_name='Payment method'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='payment_month',
            field=models.CharField(choices=[('1月份', '1月份'), ('2月份', '2月份'), ('3月份', '3月份'), ('4月份', '4月份'), ('5月份', '5月份'), ('6月份', '6月份'), ('7月份', '7月份'), ('8月份', '8月份'), ('9月份', '9月份'), ('10月份', '10月份'), ('11月份', '11月份'), ('12月份', '12月份')], default=banks.models.current_month, max_length=20, verbose_name='Payment month'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='payment_year',
            field=models.CharField(choices=[('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030'), ('2031', '2031'), ('2032', '2032'), ('2033', '2033'), ('2034', '2034')], default=banks.models.current_year, max_length=20, verbose_name='Payment year'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='resident_code',
            field=models.CharField(max_length=200, verbose_name='Resident code'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='resident_id',
            field=models.IntegerField(verbose_name='Resident ID'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='resident_name',
            field=models.CharField(max_length=200, verbose_name='Resident name'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='uploaded_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Upload date'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='user_id',
            field=models.IntegerField(blank=True, verbose_name='User ID'),
        ),
    ]
