# Generated by Django 5.1.1 on 2024-09-29 23:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='visit_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='visit_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='booking',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='title',
            field=models.CharField(choices=[('Mr', '先生'), ('Ms', '女士'), ('Mrs', '太太')], default='預約參觀選位', max_length=20),
        ),
    ]
