# Generated by Django 5.2.17 on 2026-10-06 17:16

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0003_remove_booking_visit_date_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Visit booking', 'verbose_name_plural': 'Visit bookings'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.CharField(max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='submit_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Submission date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='title',
            field=models.CharField(choices=[('Mr', '先生'), ('Ms', '女士'), ('Mrs', '太太')], default='預約參觀選位', max_length=20, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='visit_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Visit date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='visit_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Visit time'),
        ),
    ]
