# Generated by Django 5.1.1 on 2024-09-20 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_id', models.CharField(max_length=50)),
                ('resident_name', models.CharField(max_length=50)),
                ('resident_description', models.CharField(max_length=200)),
                ('resident_contact_person', models.CharField(max_length=80)),
                ('resident_contact_phone', models.CharField(max_length=100)),
                ('resident_contact_email', models.CharField(max_length=100)),
                ('resident_contact_relation', models.CharField(max_length=100)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='residents_by_username', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
