# Generated by Django 5.1.1 on 2024-09-28 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resident',
            old_name='resident_id',
            new_name='resident_code',
        ),
    ]
