# Generated by Django 5.1.1 on 2024-09-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0003_alter_resident_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='resident_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='resident_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
