# Generated by Django 5.2.17 on 2026-10-06 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0007_alter_resident_resident_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resident',
            options={'verbose_name': 'Resident', 'verbose_name_plural': 'Residents'},
        ),
        migrations.AlterField(
            model_name='resident',
            name='resident_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Resident code'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='resident_contact_email',
            field=models.CharField(max_length=100, verbose_name='Contact email'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='resident_contact_person',
            field=models.CharField(max_length=80, verbose_name='Contact person'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='resident_contact_phone',
            field=models.CharField(max_length=100, verbose_name='Contact phone'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='resident_contact_relation',
            field=models.CharField(max_length=100, verbose_name='Relationship'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='resident_description',
            field=models.CharField(max_length=200, verbose_name='Resident description'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='resident_name',
            field=models.CharField(max_length=50, verbose_name='Resident name'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User account'),
        ),
    ]
